// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for TradeSide.
const (
	TradeSideBUY  TradeSide = "BUY"
	TradeSideSELL TradeSide = "SELL"
)

// Defines values for GetLeaderboardParamsSortBy.
const (
	GetLeaderboardParamsSortByRealizedPnl   GetLeaderboardParamsSortBy = "realizedPnl"
	GetLeaderboardParamsSortByTotalPnl      GetLeaderboardParamsSortBy = "totalPnl"
	GetLeaderboardParamsSortByUnrealizedPnl GetLeaderboardParamsSortBy = "unrealizedPnl"
	GetLeaderboardParamsSortByWinRate       GetLeaderboardParamsSortBy = "winRate"
)

// Defines values for GetLeaderboardParamsSortDirection.
const (
	GetLeaderboardParamsSortDirectionAsc  GetLeaderboardParamsSortDirection = "asc"
	GetLeaderboardParamsSortDirectionDesc GetLeaderboardParamsSortDirection = "desc"
)

// Defines values for GetPersonaLeaderboardParamsSortBy.
const (
	GetPersonaLeaderboardParamsSortByRealizedPnl   GetPersonaLeaderboardParamsSortBy = "realizedPnl"
	GetPersonaLeaderboardParamsSortByTotalPnl      GetPersonaLeaderboardParamsSortBy = "totalPnl"
	GetPersonaLeaderboardParamsSortByUnrealizedPnl GetPersonaLeaderboardParamsSortBy = "unrealizedPnl"
	GetPersonaLeaderboardParamsSortByWinRate       GetPersonaLeaderboardParamsSortBy = "winRate"
)

// Defines values for GetPersonaLeaderboardParamsSortDirection.
const (
	GetPersonaLeaderboardParamsSortDirectionAsc  GetPersonaLeaderboardParamsSortDirection = "asc"
	GetPersonaLeaderboardParamsSortDirectionDesc GetPersonaLeaderboardParamsSortDirection = "desc"
)

// Defines values for GetTradesParamsSide.
const (
	GetTradesParamsSideBUY  GetTradesParamsSide = "BUY"
	GetTradesParamsSideSELL GetTradesParamsSide = "SELL"
)

// Defines values for GetTradesParamsSortBy.
const (
	Size      GetTradesParamsSortBy = "size"
	Timestamp GetTradesParamsSortBy = "timestamp"
	Value     GetTradesParamsSortBy = "value"
)

// Defines values for GetTradesParamsSortDirection.
const (
	Asc  GetTradesParamsSortDirection = "asc"
	Desc GetTradesParamsSortDirection = "desc"
)

// BackfillResult defines model for BackfillResult.
type BackfillResult struct {
	NewestTradeDate  *time.Time `json:"newestTradeDate,omitempty"`
	OldestTradeDate  *time.Time `json:"oldestTradeDate,omitempty"`
	SnapshotsCreated int        `json:"snapshotsCreated"`
	TotalRealizedPnl float64    `json:"totalRealizedPnl"`
	TradesProcessed  int        `json:"tradesProcessed"`
	Username         string     `json:"username"`
}

// LeaderboardEntry defines model for LeaderboardEntry.
type LeaderboardEntry struct {
	OpenPositions      *int     `json:"openPositions,omitempty"`
	PersonaDisplayName *string  `json:"personaDisplayName,omitempty"`
	PersonaSlug        *string  `json:"personaSlug,omitempty"`
	ProfileImage       *string  `json:"profileImage,omitempty"`
	Rank               int      `json:"rank"`
	RealizedPnl        float64  `json:"realizedPnl"`
	TotalPnl           float64  `json:"totalPnl"`
	UnrealizedPnl      float64  `json:"unrealizedPnl"`
	Username           string   `json:"username"`
	WinRate            *float64 `json:"winRate,omitempty"`
}

// PersonaAccount defines model for PersonaAccount.
type PersonaAccount struct {
	Addresses     []string `json:"addresses"`
	OpenPositions *int     `json:"openPositions,omitempty"`
	ProfileImage  *string  `json:"profileImage,omitempty"`
	RealizedPnl   float64  `json:"realizedPnl"`
	TotalPnl      float64  `json:"totalPnl"`
	TotalTrades   *int     `json:"totalTrades,omitempty"`
	UnrealizedPnl float64  `json:"unrealizedPnl"`
	Username      string   `json:"username"`
	WinRate       *float64 `json:"winRate,omitempty"`
}

// PersonaDetail defines model for PersonaDetail.
type PersonaDetail struct {
	DisplayName   string   `json:"displayName"`
	Image         *string  `json:"image,omitempty"`
	OpenPositions *int     `json:"openPositions,omitempty"`
	RealizedPnl   float64  `json:"realizedPnl"`
	Slug          string   `json:"slug"`
	TotalPnl      float64  `json:"totalPnl"`
	TotalTrades   *int     `json:"totalTrades,omitempty"`
	UnrealizedPnl float64  `json:"unrealizedPnl"`
	Usernames     []string `json:"usernames"`
	WinRate       *float64 `json:"winRate,omitempty"`
}

// PersonaLeaderboardEntry defines model for PersonaLeaderboardEntry.
type PersonaLeaderboardEntry struct {
	DisplayName   string    `json:"displayName"`
	Image         *string   `json:"image,omitempty"`
	OpenPositions *int      `json:"openPositions,omitempty"`
	Rank          int       `json:"rank"`
	RealizedPnl   float64   `json:"realizedPnl"`
	Slug          string    `json:"slug"`
	TotalPnl      float64   `json:"totalPnl"`
	UnrealizedPnl float64   `json:"unrealizedPnl"`
	Usernames     *[]string `json:"usernames,omitempty"`
	WinRate       *float64  `json:"winRate,omitempty"`
}

// PersonaPosition defines model for PersonaPosition.
type PersonaPosition struct {
	AvgPrice             float64    `json:"avgPrice"`
	ConditionId          *string    `json:"conditionId,omitempty"`
	CurrentPrice         float64    `json:"currentPrice"`
	CurrentValue         *float64   `json:"currentValue,omitempty"`
	EndDate              *time.Time `json:"endDate,omitempty"`
	Id                   string     `json:"id"`
	InitialValue         *float64   `json:"initialValue,omitempty"`
	MarketSlug           *string    `json:"marketSlug,omitempty"`
	MarketTitle          string     `json:"marketTitle"`
	Outcome              string     `json:"outcome"`
	Size                 float64    `json:"size"`
	UnrealizedPnl        float64    `json:"unrealizedPnl"`
	UnrealizedPnlPercent *float64   `json:"unrealizedPnlPercent,omitempty"`
	Username             string     `json:"username"`
}

// PersonaResult defines model for PersonaResult.
type PersonaResult struct {
	ConditionId    string     `json:"conditionId"`
	EndDate        *time.Time `json:"endDate,omitempty"`
	Id             string     `json:"id"`
	InitialValue   *float64   `json:"initialValue,omitempty"`
	MarketSlug     *string    `json:"marketSlug,omitempty"`
	MarketTitle    string     `json:"marketTitle"`
	Outcome        string     `json:"outcome"`
	RealizedPnl    float64    `json:"realizedPnl"`
	ResolutionDate *time.Time `json:"resolutionDate,omitempty"`
	Username       string     `json:"username"`
}

// PersonaResultsResponse defines model for PersonaResultsResponse.
type PersonaResultsResponse struct {
	Limit   *int            `json:"limit,omitempty"`
	Offset  *int            `json:"offset,omitempty"`
	Results []PersonaResult `json:"results"`
	Total   int             `json:"total"`
}

// PersonaSummary defines model for PersonaSummary.
type PersonaSummary struct {
	DisplayName string   `json:"displayName"`
	Image       *string  `json:"image,omitempty"`
	Slug        string   `json:"slug"`
	Usernames   []string `json:"usernames"`
}

// PnlDataPoint defines model for PnlDataPoint.
type PnlDataPoint struct {
	RealizedPnl   float64   `json:"realizedPnl"`
	Timestamp     time.Time `json:"timestamp"`
	TotalPnl      float64   `json:"totalPnl"`
	UnrealizedPnl float64   `json:"unrealizedPnl"`
}

// PnlHistory defines model for PnlHistory.
type PnlHistory struct {
	DataPoints []PnlDataPoint `json:"dataPoints"`
	Username   string         `json:"username"`
}

// Position defines model for Position.
type Position struct {
	AvgPrice             float64    `json:"avgPrice"`
	ConditionId          *string    `json:"conditionId,omitempty"`
	CurrentPrice         float64    `json:"currentPrice"`
	CurrentValue         *float64   `json:"currentValue,omitempty"`
	EndDate              *time.Time `json:"endDate,omitempty"`
	Id                   string     `json:"id"`
	InitialValue         *float64   `json:"initialValue,omitempty"`
	MarketSlug           *string    `json:"marketSlug,omitempty"`
	MarketTitle          string     `json:"marketTitle"`
	Outcome              string     `json:"outcome"`
	Size                 float64    `json:"size"`
	UnrealizedPnl        float64    `json:"unrealizedPnl"`
	UnrealizedPnlPercent *float64   `json:"unrealizedPnlPercent,omitempty"`
}

// Result defines model for Result.
type Result struct {
	ConditionId    string     `json:"conditionId"`
	EndDate        *time.Time `json:"endDate,omitempty"`
	Id             string     `json:"id"`
	InitialValue   *float64   `json:"initialValue,omitempty"`
	MarketSlug     *string    `json:"marketSlug,omitempty"`
	MarketTitle    string     `json:"marketTitle"`
	Outcome        string     `json:"outcome"`
	RealizedPnl    float64    `json:"realizedPnl"`
	ResolutionDate *time.Time `json:"resolutionDate,omitempty"`
}

// ResultsResponse defines model for ResultsResponse.
type ResultsResponse struct {
	Limit   *int     `json:"limit,omitempty"`
	Offset  *int     `json:"offset,omitempty"`
	Results []Result `json:"results"`
	Total   int      `json:"total"`
}

// Trade defines model for Trade.
type Trade struct {
	ConditionId        *string   `json:"conditionId,omitempty"`
	Id                 string    `json:"id"`
	MarketSlug         *string   `json:"marketSlug,omitempty"`
	MarketTitle        string    `json:"marketTitle"`
	Outcome            string    `json:"outcome"`
	PersonaDisplayName *string   `json:"personaDisplayName,omitempty"`
	PersonaSlug        *string   `json:"personaSlug,omitempty"`
	Price              float64   `json:"price"`
	ProfileImage       *string   `json:"profileImage,omitempty"`
	Side               TradeSide `json:"side"`
	Size               float64   `json:"size"`
	Timestamp          time.Time `json:"timestamp"`
	Username           *string   `json:"username,omitempty"`
	Value              float64   `json:"value"`
}

// TradeSide defines model for Trade.Side.
type TradeSide string

// TradesResponse defines model for TradesResponse.
type TradesResponse struct {
	Limit  *int    `json:"limit,omitempty"`
	Offset *int    `json:"offset,omitempty"`
	Total  int     `json:"total"`
	Trades []Trade `json:"trades"`
}

// User defines model for User.
type User struct {
	Addresses    []string   `json:"addresses"`
	LastSynced   *time.Time `json:"lastSynced,omitempty"`
	ProfileImage *string    `json:"profileImage,omitempty"`
	Username     string     `json:"username"`
}

// UserDetail defines model for UserDetail.
type UserDetail struct {
	Addresses     []string   `json:"addresses"`
	LastSynced    *time.Time `json:"lastSynced,omitempty"`
	OpenPositions *int       `json:"openPositions,omitempty"`
	ProfileImage  *string    `json:"profileImage,omitempty"`
	RealizedPnl   float64    `json:"realizedPnl"`
	TotalPnl      float64    `json:"totalPnl"`
	TotalTrades   *int       `json:"totalTrades,omitempty"`
	UnrealizedPnl float64    `json:"unrealizedPnl"`
	Username      string     `json:"username"`
	WinRate       *float64   `json:"winRate,omitempty"`
}

// GetLeaderboardParams defines parameters for GetLeaderboard.
type GetLeaderboardParams struct {
	SortBy        *GetLeaderboardParamsSortBy        `form:"sortBy,omitempty" json:"sortBy,omitempty"`
	SortDirection *GetLeaderboardParamsSortDirection `form:"sortDirection,omitempty" json:"sortDirection,omitempty"`
}

// GetLeaderboardParamsSortBy defines parameters for GetLeaderboard.
type GetLeaderboardParamsSortBy string

// GetLeaderboardParamsSortDirection defines parameters for GetLeaderboard.
type GetLeaderboardParamsSortDirection string

// GetPersonaLeaderboardParams defines parameters for GetPersonaLeaderboard.
type GetPersonaLeaderboardParams struct {
	SortBy        *GetPersonaLeaderboardParamsSortBy        `form:"sortBy,omitempty" json:"sortBy,omitempty"`
	SortDirection *GetPersonaLeaderboardParamsSortDirection `form:"sortDirection,omitempty" json:"sortDirection,omitempty"`
}

// GetPersonaLeaderboardParamsSortBy defines parameters for GetPersonaLeaderboard.
type GetPersonaLeaderboardParamsSortBy string

// GetPersonaLeaderboardParamsSortDirection defines parameters for GetPersonaLeaderboard.
type GetPersonaLeaderboardParamsSortDirection string

// GetPersonaResultsParams defines parameters for GetPersonaResults.
type GetPersonaResultsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetPersonaTradesParams defines parameters for GetPersonaTrades.
type GetPersonaTradesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetTradesParams defines parameters for GetTrades.
type GetTradesParams struct {
	Limit         *int                          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset        *int                          `form:"offset,omitempty" json:"offset,omitempty"`
	Username      *string                       `form:"username,omitempty" json:"username,omitempty"`
	Side          *GetTradesParamsSide          `form:"side,omitempty" json:"side,omitempty"`
	MinValue      *float64                      `form:"minValue,omitempty" json:"minValue,omitempty"`
	SortBy        *GetTradesParamsSortBy        `form:"sortBy,omitempty" json:"sortBy,omitempty"`
	SortDirection *GetTradesParamsSortDirection `form:"sortDirection,omitempty" json:"sortDirection,omitempty"`
}

// GetTradesParamsSide defines parameters for GetTrades.
type GetTradesParamsSide string

// GetTradesParamsSortBy defines parameters for GetTrades.
type GetTradesParamsSortBy string

// GetTradesParamsSortDirection defines parameters for GetTrades.
type GetTradesParamsSortDirection string

// GetUserPnlParams defines parameters for GetUserPnl.
type GetUserPnlParams struct {
	Start *time.Time `form:"start,omitempty" json:"start,omitempty"`
	End   *time.Time `form:"end,omitempty" json:"end,omitempty"`
}

// GetUserResultsParams defines parameters for GetUserResults.
type GetUserResultsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetUserTradesParams defines parameters for GetUserTrades.
type GetUserTradesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get leaderboard of all users
	// (GET /leaderboard)
	GetLeaderboard(w http.ResponseWriter, r *http.Request, params GetLeaderboardParams)
	// Get all personas (real people mapped to usernames)
	// (GET /personas)
	GetPersonas(w http.ResponseWriter, r *http.Request)
	// Get leaderboard by persona (aggregated stats)
	// (GET /personas/leaderboard)
	GetPersonaLeaderboard(w http.ResponseWriter, r *http.Request, params GetPersonaLeaderboardParams)
	// Get persona details with aggregated stats
	// (GET /personas/{slug})
	GetPersona(w http.ResponseWriter, r *http.Request, slug string)
	// Get all accounts for a persona with individual stats
	// (GET /personas/{slug}/accounts)
	GetPersonaAccounts(w http.ResponseWriter, r *http.Request, slug string)
	// Get combined positions across all accounts for a persona
	// (GET /personas/{slug}/positions)
	GetPersonaPositions(w http.ResponseWriter, r *http.Request, slug string)
	// Get combined resolved positions (results) across all accounts for a persona
	// (GET /personas/{slug}/results)
	GetPersonaResults(w http.ResponseWriter, r *http.Request, slug string, params GetPersonaResultsParams)
	// Get combined trades across all accounts for a persona
	// (GET /personas/{slug}/trades)
	GetPersonaTrades(w http.ResponseWriter, r *http.Request, slug string, params GetPersonaTradesParams)
	// Trigger a sync of all user data
	// (POST /sync)
	TriggerSync(w http.ResponseWriter, r *http.Request)
	// Get all recent trades with filtering
	// (GET /trades)
	GetTrades(w http.ResponseWriter, r *http.Request, params GetTradesParams)
	// Get all tracked users
	// (GET /users)
	GetUsers(w http.ResponseWriter, r *http.Request)
	// Get user details
	// (GET /users/{username})
	GetUser(w http.ResponseWriter, r *http.Request, username string)
	// Backfill PNL history from trade data using FIFO cost basis
	// (POST /users/{username}/backfill)
	BackfillUserPnl(w http.ResponseWriter, r *http.Request, username string)
	// Get user's PNL history
	// (GET /users/{username}/pnl)
	GetUserPnl(w http.ResponseWriter, r *http.Request, username string, params GetUserPnlParams)
	// Get user's current positions
	// (GET /users/{username}/positions)
	GetUserPositions(w http.ResponseWriter, r *http.Request, username string)
	// Get user's resolved positions (results)
	// (GET /users/{username}/results)
	GetUserResults(w http.ResponseWriter, r *http.Request, username string, params GetUserResultsParams)
	// Get user's trade history
	// (GET /users/{username}/trades)
	GetUserTrades(w http.ResponseWriter, r *http.Request, username string, params GetUserTradesParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get leaderboard of all users
// (GET /leaderboard)
func (_ Unimplemented) GetLeaderboard(w http.ResponseWriter, r *http.Request, params GetLeaderboardParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all personas (real people mapped to usernames)
// (GET /personas)
func (_ Unimplemented) GetPersonas(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get leaderboard by persona (aggregated stats)
// (GET /personas/leaderboard)
func (_ Unimplemented) GetPersonaLeaderboard(w http.ResponseWriter, r *http.Request, params GetPersonaLeaderboardParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get persona details with aggregated stats
// (GET /personas/{slug})
func (_ Unimplemented) GetPersona(w http.ResponseWriter, r *http.Request, slug string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all accounts for a persona with individual stats
// (GET /personas/{slug}/accounts)
func (_ Unimplemented) GetPersonaAccounts(w http.ResponseWriter, r *http.Request, slug string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get combined positions across all accounts for a persona
// (GET /personas/{slug}/positions)
func (_ Unimplemented) GetPersonaPositions(w http.ResponseWriter, r *http.Request, slug string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get combined resolved positions (results) across all accounts for a persona
// (GET /personas/{slug}/results)
func (_ Unimplemented) GetPersonaResults(w http.ResponseWriter, r *http.Request, slug string, params GetPersonaResultsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get combined trades across all accounts for a persona
// (GET /personas/{slug}/trades)
func (_ Unimplemented) GetPersonaTrades(w http.ResponseWriter, r *http.Request, slug string, params GetPersonaTradesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Trigger a sync of all user data
// (POST /sync)
func (_ Unimplemented) TriggerSync(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all recent trades with filtering
// (GET /trades)
func (_ Unimplemented) GetTrades(w http.ResponseWriter, r *http.Request, params GetTradesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get all tracked users
// (GET /users)
func (_ Unimplemented) GetUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user details
// (GET /users/{username})
func (_ Unimplemented) GetUser(w http.ResponseWriter, r *http.Request, username string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Backfill PNL history from trade data using FIFO cost basis
// (POST /users/{username}/backfill)
func (_ Unimplemented) BackfillUserPnl(w http.ResponseWriter, r *http.Request, username string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user's PNL history
// (GET /users/{username}/pnl)
func (_ Unimplemented) GetUserPnl(w http.ResponseWriter, r *http.Request, username string, params GetUserPnlParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user's current positions
// (GET /users/{username}/positions)
func (_ Unimplemented) GetUserPositions(w http.ResponseWriter, r *http.Request, username string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user's resolved positions (results)
// (GET /users/{username}/results)
func (_ Unimplemented) GetUserResults(w http.ResponseWriter, r *http.Request, username string, params GetUserResultsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user's trade history
// (GET /users/{username}/trades)
func (_ Unimplemented) GetUserTrades(w http.ResponseWriter, r *http.Request, username string, params GetUserTradesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLeaderboard operation middleware
func (siw *ServerInterfaceWrapper) GetLeaderboard(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLeaderboardParams

	// ------------- Optional query parameter "sortBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortBy", r.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortBy", Err: err})
		return
	}

	// ------------- Optional query parameter "sortDirection" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortDirection", r.URL.Query(), &params.SortDirection)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortDirection", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLeaderboard(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPersonas operation middleware
func (siw *ServerInterfaceWrapper) GetPersonas(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPersonas(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPersonaLeaderboard operation middleware
func (siw *ServerInterfaceWrapper) GetPersonaLeaderboard(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPersonaLeaderboardParams

	// ------------- Optional query parameter "sortBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortBy", r.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortBy", Err: err})
		return
	}

	// ------------- Optional query parameter "sortDirection" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortDirection", r.URL.Query(), &params.SortDirection)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortDirection", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPersonaLeaderboard(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPersona operation middleware
func (siw *ServerInterfaceWrapper) GetPersona(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPersona(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPersonaAccounts operation middleware
func (siw *ServerInterfaceWrapper) GetPersonaAccounts(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPersonaAccounts(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPersonaPositions operation middleware
func (siw *ServerInterfaceWrapper) GetPersonaPositions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPersonaPositions(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPersonaResults operation middleware
func (siw *ServerInterfaceWrapper) GetPersonaResults(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPersonaResultsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPersonaResults(w, r, slug, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPersonaTrades operation middleware
func (siw *ServerInterfaceWrapper) GetPersonaTrades(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPersonaTradesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPersonaTrades(w, r, slug, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerSync operation middleware
func (siw *ServerInterfaceWrapper) TriggerSync(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerSync(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrades operation middleware
func (siw *ServerInterfaceWrapper) GetTrades(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTradesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "username" -------------

	err = runtime.BindQueryParameter("form", true, false, "username", r.URL.Query(), &params.Username)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	// ------------- Optional query parameter "side" -------------

	err = runtime.BindQueryParameter("form", true, false, "side", r.URL.Query(), &params.Side)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "side", Err: err})
		return
	}

	// ------------- Optional query parameter "minValue" -------------

	err = runtime.BindQueryParameter("form", true, false, "minValue", r.URL.Query(), &params.MinValue)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "minValue", Err: err})
		return
	}

	// ------------- Optional query parameter "sortBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortBy", r.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortBy", Err: err})
		return
	}

	// ------------- Optional query parameter "sortDirection" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortDirection", r.URL.Query(), &params.SortDirection)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sortDirection", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrades(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username string

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BackfillUserPnl operation middleware
func (siw *ServerInterfaceWrapper) BackfillUserPnl(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username string

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BackfillUserPnl(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserPnl operation middleware
func (siw *ServerInterfaceWrapper) GetUserPnl(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username string

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserPnlParams

	// ------------- Optional query parameter "start" -------------

	err = runtime.BindQueryParameter("form", true, false, "start", r.URL.Query(), &params.Start)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "start", Err: err})
		return
	}

	// ------------- Optional query parameter "end" -------------

	err = runtime.BindQueryParameter("form", true, false, "end", r.URL.Query(), &params.End)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "end", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserPnl(w, r, username, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserPositions operation middleware
func (siw *ServerInterfaceWrapper) GetUserPositions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username string

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserPositions(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserResults operation middleware
func (siw *ServerInterfaceWrapper) GetUserResults(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username string

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserResultsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserResults(w, r, username, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserTrades operation middleware
func (siw *ServerInterfaceWrapper) GetUserTrades(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username string

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserTradesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserTrades(w, r, username, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/leaderboard", wrapper.GetLeaderboard)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/personas", wrapper.GetPersonas)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/personas/leaderboard", wrapper.GetPersonaLeaderboard)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/personas/{slug}", wrapper.GetPersona)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/personas/{slug}/accounts", wrapper.GetPersonaAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/personas/{slug}/positions", wrapper.GetPersonaPositions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/personas/{slug}/results", wrapper.GetPersonaResults)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/personas/{slug}/trades", wrapper.GetPersonaTrades)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/sync", wrapper.TriggerSync)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/trades", wrapper.GetTrades)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.GetUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{username}", wrapper.GetUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/{username}/backfill", wrapper.BackfillUserPnl)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{username}/pnl", wrapper.GetUserPnl)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{username}/positions", wrapper.GetUserPositions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{username}/results", wrapper.GetUserResults)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{username}/trades", wrapper.GetUserTrades)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbTW/bOhb9KwRngNcCTuy+126yS5u2EyBojXwMMGizoKVrmw1FqiTlQA383wekJIuW",
	"KFly7NQpskpsk5fkPed+8Mh+wIGIYsGBa4VPHrAK5hAR++97EtxNKWOXoBKmzTuxFDFITcF+zuEelL6W",
	"JIQzosG8NRUyIhqf4JBoONI0AjzAOo0Bn2ClJeUzvBxgwcLtJipOYjUXWn2QQDSEZmY+iHINM5BmlBaa",
	"sEsgjP6CcMzZun2RTJhjnCfRJJ9m9qPGUgSgVJPtRIHkJALn02J7ywGW8DOh0sz9Vo6sW/YcxLPr29Ue",
	"xeQHBNosfwEkBDkRRIYfuZZpHRQRAx8LRTUVXPnPEINUgpMzqmJG0i/+06yGXbFk5v9ciillcB6Rmd+A",
	"JPzOvwPZHxzjne7DE95/iRZoB/ie8ssaVRtMVYhg3TBY40NxmHVPVLftI8A4A+U0CETCPTFJwlAaktkX",
	"VEOkvMfJ3yBSktRGZAfWbIR736Da4TZrNGzxkFB34C4x2QX0Z6AJZXXkww3hTBuB6wB+f7+qprRxSKD3",
	"jJJH0MG6Y7AGkruNXRBjc23YL0V2mO13RZ7nwY28QHgp8nhaFLB5asViNpY0gI6OCQQPraXz0OuRIJES",
	"uO5lMpvyX8KSrlOAh/16RurfLeVUU8L6LB0ReQe6sR/KPr6mmjXEUKID0RB5iv6CfXLanTMGGUDWOzyu",
	"PlZoTMP1Lsf1R3n6/KyDkn0V5vSgdtPFZBNT/0wO9aeFBCVYYhzVzx3bc8JFppkhveBXl6BiwRXUecBo",
	"RLW/JonpVIFuqlfW7lr+/7eEKT7B/xqWt+VhflUerrPRUxtsEvetVS0E+cLFjJazXyVRRHZb4xuL7lYV",
	"sV//4z0pZ2dEk7GgvovOFrcNGoHSJIq7E33v7UbFS+UWH1f5OfsPVVp4+VG4tAe/XSA89N5KE3H24T3C",
	"S9fy0rVs27X4itAeu5GXNuR3tCE+kHfTXhxKX/E0DYXVVvqTt4GLeyTWzmTr7pl+o+apaOY74ElkHP7+",
	"5n94gK8+Xlw4vt4qYW7RrbRKmYvO2cEXWG5j0pxJQ/MnzvNmnlizdRuJt/soa4yN4jlM5/jLImNTZ5sb",
	"bQuxGwVyZ1I9I0pfpTzInlB1Y8ZGHm/VwpUHaDp0k1b9hEd/ebJx6E82lraFmQp7OwEVSBpnnT8eC5Zm",
	"2QbFOYRISxLcgURH6J7oYI5SkUgUCQ4pmiSS21xlqwsepxLQ6fjcJCGQKjP55nh0PCp4QWKKT/A/x6Pj",
	"f0ziInpu3T9kpZJuXs+yVGMITIqKiD+DdgR3O12SCDRIhU++PWBqVvuZgEzxAGcwYCWkfm9eZxkmO/CU",
	"2ObR9V9RTTq6tETz1tMlNW/ljEoIrKv9OzJgOLsh9pV907POre1vbCq3Tvx7NMrbCJ237SSOGQ2sB4c/",
	"VHa1K5ftlJFrjzjqyXk5qJDIRcl8qgrlxECIHKiRmCLCGDL8VnboMO8lVBsLxsWYp3BARf3pcnyqtDnZ",
	"6ih1H5hDFx+jV4ZZKAYRM0ARiWMIkRZoJdW8XvdM11ipP6N6CZnbJ2TMNpGTT3VjZEMETdKCSOgVmc0k",
	"zIiGEClNdI04D4ols2UHzjQQxaRrB5xMXyzrlJYJuBjt2vkdfJ53Py2eDe0IZcB4O3rrKYD5OC40moqE",
	"+/wfr9tC91TPUdX5Xt8PSfYtki7p7bQYepBg9ImE4qszPQJg5afH4GSybGEITYVEZAWdhYzykC5omBDW",
	"BlnstrIbMCvb3mcP2koO7oDaBxFNKIcQlb56DG5BzRwigRRKtSDqx87RfzYgd7nSbfaAW0N5y67b3rL2",
	"bjTwKE1+M/nV3GvHZ+YJ8nBVz2vjjNUiF7snT92u6bTsvl5vy6dSzthAp+tCojgINr0ZPVM6VQSrNhrl",
	"0OyEOpmtriRRKQ+s4CKUhxPXks5mIK/MoJqn/q5v1Aw05UhqqO4xN4UIMku6lycUEp3vZjNFW7l5GCmq",
	"wYyjg/QOj1wrLed1EpCbrEWUZw9/XIsdZJ1trlyOELy6cznvLYp90F/P+m71uDxwylgRtra3m1KmYSWn",
	"1vtCCQFw3TJlmIkSLXF0Ywc8RUtm1eweykOpp9QPnql5oau52H+HD0V0LTcdulNZc2L1MK6Ijjrucd2N",
	"zaIbLod2UFsFSdas+Hw7nOQ/8XErxvoqlxAIrrRMAq3Q3H6rhAaEofGXC3vdz37UQvmswNMwOJhLwQUT",
	"MzOUpcff+Y0ChT6df/qKXn2iUumjc36U/fM10a9RIJRGE6KoQlqggLAgYUQDKjQbs9zxd/4ZuGEAKBQS",
	"ylK0+hmN4VmQRGYSXdSm4UGFOsUvm4wLMznoGVKo8vMsD42KEaaXiBlYNSAJDF7ThLG0M7MG+F227wbz",
	"U0JZrT9YfWqYkhEnRVMpoowktklAiWWO5UVJgQauxtmTj7ZcsFcsm0qX6Y4aKm/btxf81oCH/W3t9Q5V",
	"fpfMp5CU2DYkoL8Uqg7yQNtF1bAA95I0fkvIdpM1eugZNhqd62iTm/PvLVWG1p3dQYYwS/bRIHYZT3+g",
	"DtFBgLjsrjt0qvt/qVbJoYEam69rZvEecsITEeMPlhQs2oWc0AR1VlHnbp5WIBcFMIlk+AQPSUyHizd4",
	"ebv8fwAAAP//qrS8YvU9AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
