// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  BackfillUserPnlData,
  BackfillUserPnlErrors,
  BackfillUserPnlResponses,
  GetLeaderboardData,
  GetLeaderboardResponses,
  GetPersonaAccountsData,
  GetPersonaAccountsErrors,
  GetPersonaAccountsResponses,
  GetPersonaData,
  GetPersonaErrors,
  GetPersonaLeaderboardData,
  GetPersonaLeaderboardResponses,
  GetPersonaPositionsData,
  GetPersonaPositionsErrors,
  GetPersonaPositionsResponses,
  GetPersonaResponses,
  GetPersonaResultsData,
  GetPersonaResultsErrors,
  GetPersonaResultsResponses,
  GetPersonasData,
  GetPersonasResponses,
  GetPersonaTradesData,
  GetPersonaTradesErrors,
  GetPersonaTradesResponses,
  GetTradesData,
  GetTradesResponses,
  GetUserData,
  GetUserErrors,
  GetUserPnlData,
  GetUserPnlResponses,
  GetUserPositionsData,
  GetUserPositionsResponses,
  GetUserResponses,
  GetUserResultsData,
  GetUserResultsErrors,
  GetUserResultsResponses,
  GetUsersData,
  GetUsersResponses,
  GetUserTradesData,
  GetUserTradesResponses,
  TriggerSyncData,
  TriggerSyncResponses,
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get all tracked users
 */
export const getUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetUsersResponses, unknown, ThrowOnError>({
    url: '/users',
    ...options,
  });
};

/**
 * Get user details
 */
export const getUser = <ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>) => {
  return (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({
    url: '/users/{username}',
    ...options,
  });
};

/**
 * Get user's current positions
 */
export const getUserPositions = <ThrowOnError extends boolean = false>(
  options: Options<GetUserPositionsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<GetUserPositionsResponses, unknown, ThrowOnError>({
    url: '/users/{username}/positions',
    ...options,
  });
};

/**
 * Get user's trade history
 */
export const getUserTrades = <ThrowOnError extends boolean = false>(
  options: Options<GetUserTradesData, ThrowOnError>,
) => {
  return (options.client ?? client).get<GetUserTradesResponses, unknown, ThrowOnError>({
    url: '/users/{username}/trades',
    ...options,
  });
};

/**
 * Get user's PNL history
 */
export const getUserPnl = <ThrowOnError extends boolean = false>(options: Options<GetUserPnlData, ThrowOnError>) => {
  return (options.client ?? client).get<GetUserPnlResponses, unknown, ThrowOnError>({
    url: '/users/{username}/pnl',
    ...options,
  });
};

/**
 * Get user's resolved positions (results)
 */
export const getUserResults = <ThrowOnError extends boolean = false>(
  options: Options<GetUserResultsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<GetUserResultsResponses, GetUserResultsErrors, ThrowOnError>({
    url: '/users/{username}/results',
    ...options,
  });
};

/**
 * Backfill PNL history from trade data using FIFO cost basis
 *
 * Reconstructs historical PNL by processing all trades chronologically.
 * Uses FIFO (First-In-First-Out) cost basis to calculate realized PNL.
 * Generates daily snapshots of cumulative realized PNL.
 *
 */
export const backfillUserPnl = <ThrowOnError extends boolean = false>(
  options: Options<BackfillUserPnlData, ThrowOnError>,
) => {
  return (options.client ?? client).post<BackfillUserPnlResponses, BackfillUserPnlErrors, ThrowOnError>({
    url: '/users/{username}/backfill',
    ...options,
  });
};

/**
 * Get all recent trades with filtering
 */
export const getTrades = <ThrowOnError extends boolean = false>(options?: Options<GetTradesData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetTradesResponses, unknown, ThrowOnError>({
    url: '/trades',
    ...options,
  });
};

/**
 * Get leaderboard of all users
 */
export const getLeaderboard = <ThrowOnError extends boolean = false>(
  options?: Options<GetLeaderboardData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetLeaderboardResponses, unknown, ThrowOnError>({
    url: '/leaderboard',
    ...options,
  });
};

/**
 * Trigger a sync of all user data
 */
export const triggerSync = <ThrowOnError extends boolean = false>(options?: Options<TriggerSyncData, ThrowOnError>) => {
  return (options?.client ?? client).post<TriggerSyncResponses, unknown, ThrowOnError>({
    url: '/sync',
    ...options,
  });
};

/**
 * Get all personas (real people mapped to usernames)
 */
export const getPersonas = <ThrowOnError extends boolean = false>(options?: Options<GetPersonasData, ThrowOnError>) => {
  return (options?.client ?? client).get<GetPersonasResponses, unknown, ThrowOnError>({
    url: '/personas',
    ...options,
  });
};

/**
 * Get persona details with aggregated stats
 */
export const getPersona = <ThrowOnError extends boolean = false>(options: Options<GetPersonaData, ThrowOnError>) => {
  return (options.client ?? client).get<GetPersonaResponses, GetPersonaErrors, ThrowOnError>({
    url: '/personas/{slug}',
    ...options,
  });
};

/**
 * Get all accounts for a persona with individual stats
 */
export const getPersonaAccounts = <ThrowOnError extends boolean = false>(
  options: Options<GetPersonaAccountsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<GetPersonaAccountsResponses, GetPersonaAccountsErrors, ThrowOnError>({
    url: '/personas/{slug}/accounts',
    ...options,
  });
};

/**
 * Get leaderboard by persona (aggregated stats)
 */
export const getPersonaLeaderboard = <ThrowOnError extends boolean = false>(
  options?: Options<GetPersonaLeaderboardData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<GetPersonaLeaderboardResponses, unknown, ThrowOnError>({
    url: '/personas/leaderboard',
    ...options,
  });
};

/**
 * Get combined positions across all accounts for a persona
 */
export const getPersonaPositions = <ThrowOnError extends boolean = false>(
  options: Options<GetPersonaPositionsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<GetPersonaPositionsResponses, GetPersonaPositionsErrors, ThrowOnError>({
    url: '/personas/{slug}/positions',
    ...options,
  });
};

/**
 * Get combined trades across all accounts for a persona
 */
export const getPersonaTrades = <ThrowOnError extends boolean = false>(
  options: Options<GetPersonaTradesData, ThrowOnError>,
) => {
  return (options.client ?? client).get<GetPersonaTradesResponses, GetPersonaTradesErrors, ThrowOnError>({
    url: '/personas/{slug}/trades',
    ...options,
  });
};

/**
 * Get combined resolved positions (results) across all accounts for a persona
 */
export const getPersonaResults = <ThrowOnError extends boolean = false>(
  options: Options<GetPersonaResultsData, ThrowOnError>,
) => {
  return (options.client ?? client).get<GetPersonaResultsResponses, GetPersonaResultsErrors, ThrowOnError>({
    url: '/personas/{slug}/results',
    ...options,
  });
};
