// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type User = {
  username: string;
  addresses: Array<string>;
  profileImage?: string;
  lastSynced?: string;
};

export type UserDetail = {
  username: string;
  addresses: Array<string>;
  profileImage?: string;
  totalPnl: number;
  realizedPnl: number;
  unrealizedPnl: number;
  openPositions?: number;
  totalTrades?: number;
  winRate?: number;
  lastSynced?: string;
};

export type Position = {
  id: string;
  conditionId?: string;
  marketTitle: string;
  marketSlug?: string;
  outcome: string;
  size: number;
  avgPrice: number;
  currentPrice: number;
  initialValue?: number;
  currentValue?: number;
  unrealizedPnl: number;
  unrealizedPnlPercent?: number;
  endDate?: string;
};

export type Trade = {
  id: string;
  username?: string;
  personaSlug?: string;
  personaDisplayName?: string;
  profileImage?: string;
  timestamp: string;
  conditionId?: string;
  marketTitle: string;
  marketSlug?: string;
  outcome: string;
  side: 'BUY' | 'SELL';
  price: number;
  size: number;
  value: number;
};

export type TradesResponse = {
  trades: Array<Trade>;
  total: number;
  limit?: number;
  offset?: number;
};

export type PnlDataPoint = {
  timestamp: string;
  totalPnl: number;
  realizedPnl: number;
  unrealizedPnl: number;
};

export type PnlHistory = {
  username: string;
  dataPoints: Array<PnlDataPoint>;
};

export type LeaderboardEntry = {
  rank: number;
  username: string;
  profileImage?: string;
  personaSlug?: string;
  personaDisplayName?: string;
  totalPnl: number;
  realizedPnl: number;
  unrealizedPnl: number;
  openPositions?: number;
  winRate?: number;
};

export type BackfillResult = {
  username: string;
  tradesProcessed: number;
  snapshotsCreated: number;
  totalRealizedPnl: number;
  oldestTradeDate?: string;
  newestTradeDate?: string;
};

export type PersonaSummary = {
  slug: string;
  displayName: string;
  image?: string;
  usernames: Array<string>;
};

export type PersonaDetail = {
  slug: string;
  displayName: string;
  image?: string;
  usernames: Array<string>;
  totalPnl: number;
  realizedPnl: number;
  unrealizedPnl: number;
  openPositions?: number;
  totalTrades?: number;
  winRate?: number;
};

export type PersonaAccount = {
  username: string;
  profileImage?: string;
  addresses: Array<string>;
  totalPnl: number;
  realizedPnl: number;
  unrealizedPnl: number;
  openPositions?: number;
  totalTrades?: number;
  winRate?: number;
};

export type PersonaLeaderboardEntry = {
  rank: number;
  slug: string;
  displayName: string;
  image?: string;
  usernames?: Array<string>;
  totalPnl: number;
  realizedPnl: number;
  unrealizedPnl: number;
  openPositions?: number;
  winRate?: number;
};

export type PersonaPosition = {
  id: string;
  username: string;
  conditionId?: string;
  marketTitle: string;
  marketSlug?: string;
  outcome: string;
  size: number;
  avgPrice: number;
  currentPrice: number;
  initialValue?: number;
  currentValue?: number;
  unrealizedPnl: number;
  unrealizedPnlPercent?: number;
  endDate?: string;
};

export type Result = {
  id: string;
  conditionId: string;
  marketTitle: string;
  marketSlug?: string;
  outcome: string;
  realizedPnl: number;
  initialValue?: number;
  endDate?: string;
  resolutionDate?: string;
};

export type ResultsResponse = {
  results: Array<Result>;
  total: number;
  limit?: number;
  offset?: number;
};

export type PersonaResult = {
  id: string;
  username: string;
  conditionId: string;
  marketTitle: string;
  marketSlug?: string;
  outcome: string;
  realizedPnl: number;
  initialValue?: number;
  endDate?: string;
  resolutionDate?: string;
};

export type PersonaResultsResponse = {
  results: Array<PersonaResult>;
  total: number;
  limit?: number;
  offset?: number;
};

export type GetUsersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/users';
};

export type GetUsersResponses = {
  /**
   * List of users
   */
  200: Array<User>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type GetUserData = {
  body?: never;
  path: {
    username: string;
  };
  query?: never;
  url: '/users/{username}';
};

export type GetUserErrors = {
  /**
   * User not found
   */
  404: unknown;
};

export type GetUserResponses = {
  /**
   * User details
   */
  200: UserDetail;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type GetUserPositionsData = {
  body?: never;
  path: {
    username: string;
  };
  query?: never;
  url: '/users/{username}/positions';
};

export type GetUserPositionsResponses = {
  /**
   * User positions
   */
  200: Array<Position>;
};

export type GetUserPositionsResponse = GetUserPositionsResponses[keyof GetUserPositionsResponses];

export type GetUserTradesData = {
  body?: never;
  path: {
    username: string;
  };
  query?: {
    limit?: number;
    offset?: number;
  };
  url: '/users/{username}/trades';
};

export type GetUserTradesResponses = {
  /**
   * User trades
   */
  200: TradesResponse;
};

export type GetUserTradesResponse = GetUserTradesResponses[keyof GetUserTradesResponses];

export type GetUserPnlData = {
  body?: never;
  path: {
    username: string;
  };
  query?: {
    start?: string;
    end?: string;
  };
  url: '/users/{username}/pnl';
};

export type GetUserPnlResponses = {
  /**
   * PNL history
   */
  200: PnlHistory;
};

export type GetUserPnlResponse = GetUserPnlResponses[keyof GetUserPnlResponses];

export type GetUserResultsData = {
  body?: never;
  path: {
    username: string;
  };
  query?: {
    limit?: number;
    offset?: number;
  };
  url: '/users/{username}/results';
};

export type GetUserResultsErrors = {
  /**
   * User not found
   */
  404: unknown;
};

export type GetUserResultsResponses = {
  /**
   * Resolved positions
   */
  200: ResultsResponse;
};

export type GetUserResultsResponse = GetUserResultsResponses[keyof GetUserResultsResponses];

export type BackfillUserPnlData = {
  body?: never;
  path: {
    username: string;
  };
  query?: never;
  url: '/users/{username}/backfill';
};

export type BackfillUserPnlErrors = {
  /**
   * User not found
   */
  404: unknown;
  /**
   * Backfill failed
   */
  500: unknown;
};

export type BackfillUserPnlResponses = {
  /**
   * Backfill completed successfully
   */
  200: BackfillResult;
};

export type BackfillUserPnlResponse = BackfillUserPnlResponses[keyof BackfillUserPnlResponses];

export type GetTradesData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    offset?: number;
    username?: string;
    side?: 'BUY' | 'SELL';
    minValue?: number;
    sortBy?: 'timestamp' | 'value' | 'size';
    sortDirection?: 'asc' | 'desc';
  };
  url: '/trades';
};

export type GetTradesResponses = {
  /**
   * All trades with filtering
   */
  200: TradesResponse;
};

export type GetTradesResponse = GetTradesResponses[keyof GetTradesResponses];

export type GetLeaderboardData = {
  body?: never;
  path?: never;
  query?: {
    sortBy?: 'totalPnl' | 'realizedPnl' | 'unrealizedPnl' | 'winRate';
    sortDirection?: 'asc' | 'desc';
  };
  url: '/leaderboard';
};

export type GetLeaderboardResponses = {
  /**
   * Leaderboard
   */
  200: Array<LeaderboardEntry>;
};

export type GetLeaderboardResponse = GetLeaderboardResponses[keyof GetLeaderboardResponses];

export type TriggerSyncData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/sync';
};

export type TriggerSyncResponses = {
  /**
   * Sync started
   */
  202: unknown;
};

export type GetPersonasData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/personas';
};

export type GetPersonasResponses = {
  /**
   * List of personas
   */
  200: Array<PersonaSummary>;
};

export type GetPersonasResponse = GetPersonasResponses[keyof GetPersonasResponses];

export type GetPersonaData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/personas/{slug}';
};

export type GetPersonaErrors = {
  /**
   * Persona not found
   */
  404: unknown;
};

export type GetPersonaResponses = {
  /**
   * Persona details
   */
  200: PersonaDetail;
};

export type GetPersonaResponse = GetPersonaResponses[keyof GetPersonaResponses];

export type GetPersonaAccountsData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/personas/{slug}/accounts';
};

export type GetPersonaAccountsErrors = {
  /**
   * Persona not found
   */
  404: unknown;
};

export type GetPersonaAccountsResponses = {
  /**
   * Persona accounts
   */
  200: Array<PersonaAccount>;
};

export type GetPersonaAccountsResponse = GetPersonaAccountsResponses[keyof GetPersonaAccountsResponses];

export type GetPersonaLeaderboardData = {
  body?: never;
  path?: never;
  query?: {
    sortBy?: 'totalPnl' | 'realizedPnl' | 'unrealizedPnl' | 'winRate';
    sortDirection?: 'asc' | 'desc';
  };
  url: '/personas/leaderboard';
};

export type GetPersonaLeaderboardResponses = {
  /**
   * Persona leaderboard
   */
  200: Array<PersonaLeaderboardEntry>;
};

export type GetPersonaLeaderboardResponse = GetPersonaLeaderboardResponses[keyof GetPersonaLeaderboardResponses];

export type GetPersonaPositionsData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: never;
  url: '/personas/{slug}/positions';
};

export type GetPersonaPositionsErrors = {
  /**
   * Persona not found
   */
  404: unknown;
};

export type GetPersonaPositionsResponses = {
  /**
   * Combined positions
   */
  200: Array<PersonaPosition>;
};

export type GetPersonaPositionsResponse = GetPersonaPositionsResponses[keyof GetPersonaPositionsResponses];

export type GetPersonaTradesData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: {
    limit?: number;
    offset?: number;
  };
  url: '/personas/{slug}/trades';
};

export type GetPersonaTradesErrors = {
  /**
   * Persona not found
   */
  404: unknown;
};

export type GetPersonaTradesResponses = {
  /**
   * Combined trades
   */
  200: TradesResponse;
};

export type GetPersonaTradesResponse = GetPersonaTradesResponses[keyof GetPersonaTradesResponses];

export type GetPersonaResultsData = {
  body?: never;
  path: {
    slug: string;
  };
  query?: {
    limit?: number;
    offset?: number;
  };
  url: '/personas/{slug}/results';
};

export type GetPersonaResultsErrors = {
  /**
   * Persona not found
   */
  404: unknown;
};

export type GetPersonaResultsResponses = {
  /**
   * Combined resolved positions
   */
  200: PersonaResultsResponse;
};

export type GetPersonaResultsResponse = GetPersonaResultsResponses[keyof GetPersonaResultsResponses];
